### ISSUE TITLE
Robot and Marbles Tutorial in the 'cadCAD-org/demos' repo

### ISSUE THREAD

**Issue by mzargham** [cadCAD-org/demos#1]
pip install cadCAD and verify that the version is 0.4.17
to force the version do:
`pip install cadCAD == 0.4.17`

to check the version do:
`pip freeze`

Download the last version of the robot and marbles tutorials folder found here:
[https://github.com/cadCAD-org/cadCAD/tree/os_release/tutorials](https://github.com/cadCAD-org/cadCAD/tree/os_release/tutorials)

Download a cadCAD notebook that runs in version 0.4.xx such as:
[https://github.com/DAOresearch/credcastle/blob/master/credcastle-2.ipynb](https://github.com/DAOresearch/credcastle/blob/master/credcastle-2.ipynb)

Check that the configuration objects are valid and make changes if necessary to get the tutorials to run; documentation can be found here: [https://github.com/cadCAD-org/cadCAD/blob/master/documentation/Simulation_Execution.md](https://github.com/cadCAD-org/cadCAD/blob/master/documentation/Simulation_Execution.md)

here is an example:
```
from cadCAD.engine import ExecutionMode, ExecutionContext
exec_mode = ExecutionMode()
local_mode_ctx = ExecutionContext(context=exec_mode.local_mode)

from cadCAD.engine import Executor
from cadCAD import configs
simulation = Executor(exec_context=local_mode_ctx, configs=configs)

append_configs(
    initial_state=initial_conditions, #dict containing variable names and initial values
    partial_state_update_blocks=partial_state_update_blocks, #dict containing state update functions
    sim_configs=simulation_parameters #dict containing simulation parameters
)

raw_system_events, tensor_field, sessions = simulation.execute()
simulation_result = pd.DataFrame(raw_system_events)
```

one import change to note is to make sure to update the block of code that called the cadCAD engine to match the new 3 output format.

Work through the robot and marbles tutorials 1 through 6 and make sure they run. Once modified and verified as running in cadCAD 0.4.17 make a pull request to merge them into the demos repo:

cadCAD-org/demos/tutorials/robot-marbles/...<files go here>

**Comment by mzargham** [comment]
@jzaki -- laid out as much detail as i could to make it easy. We've rewired some of the complex run multiple experiments at once features so some of the plotting may break -- fixes are minor data munging but you may need input from @markusbkoch @matttyb80 or @JEJodesty if you get stuck. 

@griffgreen -- when is your workshop scheduled?

**Comment by GriffGreen** [comment]
I have not scheduled it but I will when I know I can do it :-D 

Peth, Burrata and Yalor have all been pushing the Commons Stack to do a workshop... The expected date would be next week, but I will need to attempt to do the tutorial on the weekend...

So i would say the latest date this will work to be done is Thursday so that I can try to get it working on Friday and schedule the workshop for the week after.

**Comment by jzaki** [comment]
I've looked into how configs works under the hood, and have kept the original `Configuration` initialisation in tut1 [here](https://github.com/jzaki/cadCAD/blob/os_release/tutorials/robot-marbles-part-1/robot-marbles-part-1.ipynb?short_path=0f993f3#L219)
If `append_configs` must be used, I'd have to clear the configs array between uses in this tutorial.

**Comment by jzaki** [comment]
Also, [here](https://github.com/jzaki/cadCAD/blob/os_release/tutorials/robot-marbles-part-1/robot-marbles-part-1.ipynb?short_path=0f993f3#L243) I left it to use `single_proc`, should this be changed to `local_mode`? Both still seem to be valid in cadCAD.

**Comment by markusbkoch** [comment]
Thanks @jzaki .

> If `append_configs` must be used, I'd have to clear the configs array between uses in this tutorial.  

I'd say we start using `append_configs` in the tutorials

> Also, [here](https://github.com/jzaki/cadCAD/blob/os_release/tutorials/robot-marbles-part-1/robot-marbles-part-1.ipynb?short_path=0f993f3#L243) I left it to use `single_proc`, should this be changed to `local_mode`? Both still seem to be valid in cadCAD.  

If I understand correctly, `single_proc` is there for backwards compatibility but `local_mode` should be preferred. Can you confirm, @JEJodesty?

**Comment by markusbkoch** [comment]
I also want to flag that the resulting dataset is slightly different than the original one
| [Original](https://github.com/jzaki/cadCAD/blob/8bcbfae0f3c24358c392f07fb0d44b3b7f66a885/tutorials/robot-marbles-part-1/robot-marbles-part-1.ipynb)  | [Change](https://github.com/jzaki/cadCAD/blob/24f5146eb611c27a8e88f8f084a719ac6839cae9/tutorials/robot-marbles-part-1/robot-marbles-part-1.ipynb) |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/34865315/87251238-86fe8680-c440-11ea-9ed9-c6485bca8467.png)  | ![image](https://user-images.githubusercontent.com/34865315/87251230-79e19780-c440-11ea-9a89-bfd57f0cf63b.png)  |

The new column `simulation` should probably be added to the index as its first level. But I'm not sure what's wrong with the `run` column. cc @JEJodesty @matttyb80

**Comment by jzaki** [comment]
Tutorials 1-3 [updated](https://github.com/jzaki/cadCAD/commit/8cfe7153ffa5c971c25665eee46fe33db82f9a83) using `append_configs` and `local_mode`.
To display using existing code, `df` was set per simulation index.

**Note**: Tutorial 2 errors on the third `execute()`:
```
TypeError                                 Traceback (most recent call last)
 in 
     26 
     27 executor = Executor(exec_context, configs) # Pass the configuration object inside an array
---> 28 raw_result, tensor, sessions = executor.execute()...

cadCAD/engine/__init__.py in get_final_results(simulations, psus, eps, sessions, remote_threshold)
    102         def get_final_results(simulations, psus, eps, sessions, remote_threshold):
    103             flat_timesteps, tensor_fields = [], []
--> 104             for sim_result, psu, ep in list(zip(simulations, psus, eps)):
    105                 flat_timesteps.append(flatten(sim_result))
    106                 tensor_fields.append(create_tensor_field(psu, ep))

TypeError: zip argument #1 must support iteration
```
The original use of `Configuration` had worked for all three.
Also, if the second execute is commented out, the third (now second run) of execute does work.

**Comment by jzaki** [comment]
Tutorials 4-6 now have [similar amendments](https://github.com/jzaki/cadCAD/commit/de51c82eb7b181a25bdff664af5447b3f13a35b1), but yield different issues.
Part 4 runs, but does not show as much randomness as I recall this tutorial having.
Part 6 now uses `multi_mode` (instead of `local_mode`), but throws a pool error (`ValueError: Pool not running`) from within the engine.
@markusbkoch @JEJodesty ?

**Comment by GriffGreen** [comment]
AMAZING WORK JAMES!

**Comment by jzaki** [comment]
@markusbkoch https://github.com/cadCAD-org/cadCAD/pull/148

**Comment by markusbkoch** [comment]
Thanks James! I plan to look into it later today.

**Comment by markusbkoch** [comment]
There seems to be an issue with 0.4.17. We're working on it.
