### ISSUE TITLE
The link is broken.

### ISSUE THREAD

**Issue by Naokiakazawa** [cadCAD-org/demos#26]
The link to the video folder is broken.
>Check out the videos folder for detailed walkthroughs of each one of the tutorials.

This is in the **Robot and Marbles Tutorial Series** section. I think it's because the video folder is not in the tutorials directory.

**Comment by Naokiakazawa** [comment]
This is in the **Tutorials** chapter.

**Comment by danlessa** [comment]
solved by #30
