### ISSUE TITLE
Update Robot and Marbles to run in Google Colab

### ISSUE THREAD

**Issue by markusbkoch** [cadCAD-org/demos#3]
(previously https://github.com/cadCAD-org/cadCAD/issues/86)

Update all the robot and marbles tutorials so that they immediately run in Google Colab from a URL like https://colab.research.google.com/github/BlockScience/cadCAD/blob/master/tutorials/robot-marbles-part-1/robot-marbles-part-1.ipynb

This would require adding a cell in the notebook that pip installs cadCAD
```
%%capture #avoid printing the output of pip install
!pip install cadCAD
```

Add direct links to the top of every notebook and to the README

**Comment by tylerdmace** [comment]
Is any one actively working on this issue at the moment?

**Comment by markusbkoch** [comment]
Not that I know of. I don't think so.

**Comment by tylerdmace** [comment]
Great. I'll take a stab at it.

**Comment by rogervs** [comment]
This has been handled in #35  -  #41 . This issue can be closed
